### PR TITLE
update to authenticate in api router

### PR DESCRIPTION
**Pull request by festinalente91**
- previously, it authenticated token in index.js which make to use global error handler.
- So I moved the authenticate middleware function to api-route.js.

### CODE REVIEW

**Review by hewonjeong — COMMENTED** [review]
LGTM🎉

**Comment by ovekyc** [comment]
Why did you move it?

**Comment by festinalente91** [comment]
@ovekyc to hanlder the authenticat errors on API error handler

**Comment by ovekyc** [comment]
Opps, Sorry my bad.
LGTM

**Comment by ovekyc** [comment]
LGTM

**Comment by ovekyc** [comment]
this is my LGTM

**Pull request merged**
