### PR TITLE
Config/env setting

### PR DESCRIPTION
**Pull request by festinalente91**
NODE_ENV=somthing is only temporary environment for one command.
So if you command like NODE_ENV=test && gulp test
gulp test's NODE_ENV is not test.(it's default NODE_ENV which is production)

References
NODE_ENV : http://www.hacksparrow.com/running-express-js-in-production-mode.html
&& in bash : http://stackoverflow.com/a/4510655

### CODE REVIEW

**Comment by fguy** [comment]
LGTM

**Comment by ovekyc** [comment]
LGTM

**Comment by festinalente91** [comment]
@fguy @ovekyc  I need LGTM again :)

**Comment by festinalente91** [comment]
Never mind lol

**Pull request merged**
