### PR TITLE
Api/test

### PR DESCRIPTION
**Pull request by festinalente91**
## Updated item api ( http get )

Yet, backend engineers didn't reached the conclusion about 
- Error code
- Indexing.

After we finish this basic flow, we will continually fill out the details :)

@fguy @shberry16 @ethkim @elegant651 @ovekyc @ochanje210 @HewonJeong

### CODE REVIEW

**Comment by fguy** [comment]
This PR is mostly duplicated with https://github.com/sv-bootcamp/goober/pull/11. Please discard duplicates.

**Comment by fguy** [comment]
Please start over when you create a feature branch (git checkout master; git checkout -b 'feature/branchname'), do not reuse the merged feature branch.

**Comment by festinalente91** [comment]
Right...  @ovekyc @HewonJeong and I were trying to commit with this one branch. 
Next time we should seperate branch more smaller. :)

**Comment by fguy** [comment]
@festinalente91 You can do it now. Do cherry picking.

**Pull request closed without merging**
