### PR TITLE
Change log file name

### PR DESCRIPTION
**Pull request by ovekyc**
Remove created-logfile
and 
edit date format
from mm-dd-yyyy
to dd-mm-yyyy

### CODE REVIEW

**Comment by ochanje210** [comment]
what is the reason for having dd-mm-yyyy format over mm-dd-yyyy?

**Comment by ovekyc** [comment]
is dd-mm-yyyy more general? 
or yyyy-mm-dd

mm-dd-year seems like mixed. confused

**Comment by ochanje210** [comment]
there is no right or wrong answer but, just let you know MDY format is being used in north america. https://en.wikipedia.org/wiki/Date_format_by_country

**Review by festinalente91 — COMMENTED** [review]
lgtm

**Comment by ochanje210** [comment]
lgtm

**Comment by festinalente91** [comment]
By the way, I think we need more discussion because there will be several server now.

**Comment by ovekyc** [comment]
lgtm

**Pull request merged**
