### PR TITLE
added rule in gulpfile

### PR DESCRIPTION
**Pull request by elegant651**
https://trello.com/c/kSrb5bUl/72-1-as-a-frontend-developer-i-d-like-to-make-building-process-for-css-with-gulp-so-that-i-can-modulize-common-css-on-that-project-

added rule in gulpfile & created css file in stylesheets folder and connect it

### CODE REVIEW

**Comment by fguy** [comment]
Where are tests?

**Comment by fguy** [comment]
Please split this pull request into MapCard and css or more. One pull request should have one feature (story).

**Comment by elegant651** [comment]
Alright, you mean that should creating separate pull request per each story on trello. I should have consider which commits are included in the pull request.

**Comment by fguy** [comment]
It's a good opportunity to try cherrypicking!

**Comment by elegant651** [comment]
I already merged via cherrypick for specific commit onto master. I'll create new pull request for other story. Will close this PR.

**Pull request closed without merging**
