### PR TITLE
Update items router

### PR DESCRIPTION
**Pull request by festinalente91**
update /items/:id get router

### CODE REVIEW

**Comment by ovekyc** [comment]
LGTM

**Comment by fguy** [comment]
Tests?

**Comment by festinalente91** [comment]
not a test. I've just forgot to connect controller

**Comment by fguy** [comment]
Please add a test case.

**Comment by festinalente91** [comment]
I already have a test, but I only forgot to add controller to router. :)
And I included this PR to [PR#30](https://github.com/sv-bootcamp/goober/pull/30)

**Comment by fguy** [comment]
It is weird. Any change should break test case.
- Taehoon

**Pull request closed without merging**
